# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and Test

on:
  workflow_call: {}  # Allow reusing this workflow
  push:
    branches:
      - master       # Run for pushes to master
      - ci           # Run for pushes to ci branch
    tags:
      - v*           # Run for version tags
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests

permissions: read-all

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore NuGet Package Cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore dependencies
        run: dotnet restore FluxMcp.sln

      - name: Build solution
        run: dotnet build --no-restore --configuration StubRelease

      - name: Run FluxMcp.Tests
        run: dotnet test FluxMcp.sln --no-restore --no-build --configuration StubRelease --logger trx --results-directory TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults/**/*.trx
          retention-days: 7

      - name: Save NuGet Package Cache
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/cache/save@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
